title: Evaluation of Emerging Educational Technologies in the Classroom
description: Workshop as part of IDC2020, June 21, London UK
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
