title: Evaluation of Emerging Educational Technologies in the Classroom
description: Workshop as part of [IDC 2020] (https://idc.acm.org/2020/), June 21, London UK
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
